Use tasks file format for dev tooling instead of individual scipts

diff --git a/scripts/circle-ci/circle-ci-auto-merge b/scripts/circle-ci/circle-ci-auto-merge
--- a/scripts/circle-ci/circle-ci-auto-merge
+++ b/scripts/circle-ci/circle-ci-auto-merge
@@ -3,8 +3,8 @@
 
 # Ensure in PR
 if [ -z "$CIRCLE_PULL_REQUEST" ]; then
-    >&2 echo 'Not in pull request, skipping automerge'
-    exit 1
+  >&2 echo 'Not in pull request, skipping automerge'
+  exit 1
 fi
 
 # Ensure all required environment variables are present
@@ -14,15 +14,15 @@ if [ -z "$CIRCLE_PROJECT_REPONAME" ] || \
     [ -z "$CIRCLE_BRANCH" ] || \
     [ -z "$CIRCLE_SHA1" ] || \
     [ -z "$GITHUB_SECRET_TOKEN" ]; then
-    >&2 echo 'Required variable unset, automerging failed'
-    exit 1
+  >&2 echo 'Required variable unset, automerging failed'
+  exit 1
 fi
 
 # Extract GitHub PR number
 github_pr_number="$(echo "$CIRCLE_PULL_REQUEST" | sed -n 's/^.*\/\([0-9]\+\)$/\1/p')"
 if [ -z "$github_pr_number" ]; then
-    >&2 echo 'GitHub PR number not found'
-    exit 1
+  >&2 echo 'GitHub PR number not found'
+  exit 1
 fi
 
 # Fetch target branch name
@@ -31,8 +31,8 @@ chmod +x jq
 url="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$github_pr_number"
 target_branch=$(curl -H "Authorization: $GITHUB_SECRET_TOKEN" "$url" | ./jq '.base.ref' | tr -d '"')
 if [ -z "$target_branch" ]; then
-    >&2 echo 'Failed to fetch GitHub PR target branch'
-    exit 1
+  >&2 echo 'Failed to fetch GitHub PR target branch'
+  exit 1
 fi
 
 echo : "
